# Generated by Django 3.1.6 on 2021-03-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj1_app', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
